# Generated by Django 4.2.7 on 2025-09-10 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('company_name', models.CharField(max_length=200)),
                ('exchange', models.CharField(max_length=20)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('market_cap', models.BigIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stock Symbol',
                'verbose_name_plural': 'Stock Symbols',
                'db_table': 'stock_symbol',
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='UserWatchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Watchlist',
                'verbose_name_plural': 'User Watchlists',
                'db_table': 'user_watchlist',
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('change', models.DecimalField(decimal_places=4, max_digits=12)),
                ('change_percent', models.DecimalField(decimal_places=2, max_digits=6)),
                ('volume', models.BigIntegerField()),
                ('market_cap', models.BigIntegerField(blank=True, null=True)),
                ('pe_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('fifty_two_week_high', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('fifty_two_week_low', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('symbol', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='market_data', to='stock_analysis.stocksymbol')),
            ],
            options={
                'verbose_name': 'Market Data',
                'verbose_name_plural': 'Market Data',
                'db_table': 'market_data',
            },
        ),
        migrations.CreateModel(
            name='AnalysisRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('analysis_type', models.CharField(choices=[('technical', 'Technical Analysis'), ('fundamental', 'Fundamental Analysis'), ('sentiment', 'Sentiment Analysis'), ('comprehensive', 'Comprehensive Analysis')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('timeframe', models.CharField(default='1y', max_length=10)),
                ('custom_prompt', models.TextField(blank=True)),
                ('result_data', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_time', models.DurationField(blank=True, null=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_analysis.stocksymbol')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analysis Request',
                'verbose_name_plural': 'Analysis Requests',
                'db_table': 'analysis_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WatchlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('price_alert_high', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('price_alert_low', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('volume_alert', models.BigIntegerField(blank=True, null=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_analysis.stocksymbol')),
                ('watchlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stock_analysis.userwatchlist')),
            ],
            options={
                'verbose_name': 'Watchlist Item',
                'verbose_name_plural': 'Watchlist Items',
                'db_table': 'watchlist_item',
                'ordering': ['added_at'],
                'unique_together': {('watchlist', 'symbol')},
            },
        ),
        migrations.CreateModel(
            name='TechnicalIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sma_20', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('sma_50', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('sma_200', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('ema_12', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('ema_26', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('rsi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('macd', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('macd_signal', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('macd_histogram', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('bb_upper', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('bb_middle', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('bb_lower', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('volume_sma', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='stock_analysis.stocksymbol')),
            ],
            options={
                'verbose_name': 'Technical Indicator',
                'verbose_name_plural': 'Technical Indicators',
                'db_table': 'technical_indicator',
                'ordering': ['-date'],
                'unique_together': {('symbol', 'date')},
            },
        ),
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('high_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('low_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('close_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('volume', models.BigIntegerField()),
                ('adjusted_close', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_data', to='stock_analysis.stocksymbol')),
            ],
            options={
                'verbose_name': 'Stock Data',
                'verbose_name_plural': 'Stock Data',
                'db_table': 'stock_data',
                'ordering': ['-date'],
                'unique_together': {('symbol', 'date')},
            },
        ),
    ]
