# Generated by Django 4.2.7 on 2025-09-10 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock_analysis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('provider', models.CharField(max_length=50)),
                ('model_id', models.CharField(max_length=100)),
                ('max_tokens', models.IntegerField(default=4000)),
                ('temperature', models.FloatField(default=0.1)),
                ('is_active', models.BooleanField(default=True)),
                ('cost_per_token', models.DecimalField(decimal_places=6, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'AI Model',
                'verbose_name_plural': 'AI Models',
                'db_table': 'ai_model',
            },
        ),
        migrations.CreateModel(
            name='AIResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('response_time', models.DurationField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('raw_response', models.TextField()),
                ('processed_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('analysis_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_response', to='stock_analysis.analysisrequest')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_insights.aimodel')),
            ],
            options={
                'verbose_name': 'AI Response',
                'verbose_name_plural': 'AI Responses',
                'db_table': 'ai_response',
            },
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('analysis_type', models.CharField(choices=[('technical', 'Technical Analysis'), ('fundamental', 'Fundamental Analysis'), ('sentiment', 'Sentiment Analysis'), ('comprehensive', 'Comprehensive Analysis')], max_length=20)),
                ('template', models.TextField()),
                ('variables', models.JSONField(default=list)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prompt Template',
                'verbose_name_plural': 'Prompt Templates',
                'db_table': 'prompt_template',
                'unique_together': {('name', 'analysis_type')},
            },
        ),
        migrations.CreateModel(
            name='InsightMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('technical_score', models.FloatField(blank=True, null=True)),
                ('momentum_score', models.FloatField(blank=True, null=True)),
                ('volatility_score', models.FloatField(blank=True, null=True)),
                ('risk_score', models.FloatField(blank=True, null=True)),
                ('recommendation', models.CharField(blank=True, choices=[('strong_buy', 'Strong Buy'), ('buy', 'Buy'), ('hold', 'Hold'), ('sell', 'Sell'), ('strong_sell', 'Strong Sell')], max_length=20, null=True)),
                ('price_target', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ai_response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='ai_insights.airesponse')),
            ],
            options={
                'verbose_name': 'Insight Metric',
                'verbose_name_plural': 'Insight Metrics',
                'db_table': 'insight_metric',
            },
        ),
        migrations.CreateModel(
            name='AnalysisPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_text', models.TextField()),
                ('variables_used', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('analysis_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prompt', to='stock_analysis.analysisrequest')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_insights.prompttemplate')),
            ],
            options={
                'verbose_name': 'Analysis Prompt',
                'verbose_name_plural': 'Analysis Prompts',
                'db_table': 'analysis_prompt',
            },
        ),
        migrations.CreateModel(
            name='ModelUsageStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_requests', models.IntegerField(default=0)),
                ('successful_requests', models.IntegerField(default=0)),
                ('failed_requests', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('total_cost', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('avg_response_time', models.DurationField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_stats', to='ai_insights.aimodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Model Usage Stats',
                'verbose_name_plural': 'Model Usage Stats',
                'db_table': 'model_usage_stats',
                'unique_together': {('model', 'user', 'date')},
            },
        ),
    ]
